### PR TITLE
Style

### PR DESCRIPTION
**Pull request by bencbernstein**

### CODE REVIEW

**Comment by OLI9292** [comment]
on / I'd throw min widths on some elements
like the buttons so they stay same height:
screen shot 2017-08-25 at 4 00 21 pm

also maybe the logo so it doesn't shrink so much

**Comment by OLI9292** [comment]
button highlights on hover might be nice

**Comment by OLI9292** [comment]
the Bring to my School green doesn't look like wordcraft green

**Comment by OLI9292** [comment]
imo game buttons look a little too big

**Comment by OLI9292** [comment]
links are getting kinda cutoff at the bottom in game
screen shot 2017-08-25 at 4 05 18 pm

**Comment by OLI9292** [comment]
seems minor but i would think itd be a big aesthetical improvement if the timer and scoreboard stayed consistently aligned left / right respectively.  the way they shift is kind of ugly

**Comment by OLI9292** [comment]
should add `cursor: pointer` for download ios link

**Comment by OLI9292** [comment]
download ios should open in new tab

**Comment by OLI9292** [comment]
would be good to get /bringToMySchool looking more like in the figma in terms of input size, no ugly blue border, cursor on submit, honey Wordcraft, etc.

**Comment by OLI9292** [comment]
currently not responsive for iPhone 6 / 7
screen shot 2017-08-25 at 4 09 56 pm

**Comment by bencbernstein** [comment]
obviously a lot more little tweaking for different devices but i think this feels generally good and legible across the board

**Pull request merged**
